#!/usr/bin/env php
<?php

declare(strict_types=1);

require dirname(__DIR__).'/vendor/autoload.php';

if (!class_exists('Symfony\Component\Dotenv\Dotenv')) {
    throw new RuntimeException('Symfony Dotenv Component is required');
}
(new Symfony\Component\Dotenv\Dotenv())->bootEnv(dirname(__DIR__).'/.env');

system(sprintf('docker exec -it %s bin/console %s', $_SERVER['PHP_CONTAINER_NAME'], implode(' ', array_slice($argv, 1))));
